vich_uploader:
    db_driver: orm

    mappings:
       products:
            uri_prefix: /asserts/pictures
            upload_destination: '%kernel.project_dir%/public/asserts/pictures'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
